"""Daily digest writer.

Reads the SQLite audit DB + sweeper state + processor outcomes, writes a
human-readable markdown summary to the canonical Brain wiki changelog.

This is the LAST step in the daily routine. By the time it runs:
- Sweeper has logged new-file inventory deltas
- Router has logged classification decisions
- Processor has invoked any `/extract-*` skills + logged the resulting atoms
- Enricher has re-bootstrapped BDG + re-loaded Neo4j
"""
from __future__ import annotations

import sqlite3
from datetime import date, datetime
from pathlib import Path
from typing import Optional


BRAIN_PATH = Path("/Users/erichroepke/Desktop/ZEUS-BRAIN-STARTUP-2026-05-17/Brain")
CHANGELOG_DIR = BRAIN_PATH / "wiki" / "Meta" / "Changelogs"
AUDIT_DB = Path(__file__).resolve().parent.parent / "data" / "daily_audit.db"


def _safe_query(db: Path, sql: str, params: tuple = ()) -> list[tuple]:
    """Run a read-only query; return [] if DB doesn't exist or table missing."""
    if not db.exists():
        return []
    try:
        with sqlite3.connect(db) as conn:
            return list(conn.execute(sql, params).fetchall())
    except sqlite3.OperationalError:
        return []


def _relative_brain_parent(path_text: str) -> str:
    """Return the destination directory relative to Brain when possible."""
    try:
        path = Path(path_text)
        parent = path.parent
        return str(parent.relative_to(BRAIN_PATH))
    except (TypeError, ValueError):
        return str(Path(path_text).parent)


def _ingest_action_rows(db: Path, run_date: str, action_prefix: str) -> list[tuple]:
    """Read live processor audit rows from the current ingest_actions schema."""
    return _safe_query(
        db,
        """
        SELECT action, src_path, dst_path, skill
        FROM ingest_actions
        WHERE run_date = ? AND action LIKE ?
        """,
        (run_date, f"{action_prefix}%"),
    )


def write_digest(run_date: Optional[date] = None) -> Path:
    """Write daily-YYYY-MM-DD.md to Brain/wiki/Meta/Changelogs/.

    Returns the path written.
    """
    run_date = run_date or date.today()
    date_str = run_date.isoformat()
    CHANGELOG_DIR.mkdir(parents=True, exist_ok=True)
    out_path = CHANGELOG_DIR / f"daily-{date_str}.md"

    # Collect stats from audit DB. Each section gracefully degrades if a table is missing.
    swept = _safe_query(
        AUDIT_DB,
        "SELECT count(*) FROM sweeper_events WHERE date(ts) = ?",
        (date_str,),
    )
    routed = _safe_query(
        AUDIT_DB,
        "SELECT destination, count(*) FROM router_decisions WHERE date(ts) = ? GROUP BY destination ORDER BY count(*) DESC",
        (date_str,),
    )
    processed = _safe_query(
        AUDIT_DB,
        "SELECT skill, count(*) FROM processor_invocations WHERE date(ts) = ? GROUP BY skill",
        (date_str,),
    )
    enriched = _safe_query(
        AUDIT_DB,
        "SELECT step, status, count(*) FROM enricher_runs WHERE date(ts) = ? GROUP BY step, status",
        (date_str,),
    )

    n_swept = swept[0][0] if swept else 0
    if not swept:
        copied_rows = _ingest_action_rows(AUDIT_DB, date_str, "COPY")
        n_swept = len({row[1] for row in copied_rows})
        routed_counts: dict[str, int] = {}
        for _, _, dst_path, _ in copied_rows:
            if dst_path:
                dest = _relative_brain_parent(dst_path)
                routed_counts[dest] = routed_counts.get(dest, 0) + 1
        routed = sorted(routed_counts.items(), key=lambda item: item[1], reverse=True)

    if not processed:
        skill_rows = _ingest_action_rows(AUDIT_DB, date_str, "SKILL:")
        skill_counts: dict[str, int] = {}
        for action, _, _, skill in skill_rows:
            skill_name = skill or action.removeprefix("SKILL:")
            skill_counts[skill_name] = skill_counts.get(skill_name, 0) + 1
        processed = sorted(skill_counts.items(), key=lambda item: item[0])

    # Build markdown
    lines = [
        "---",
        f"date: {date_str}",
        f"generated_at: {datetime.utcnow().isoformat()}Z",
        "type: daily-routine-digest",
        "kind: changelog",
        "---",
        "",
        f"# Daily Routine — {date_str}",
        "",
        f"Generated by `/Users/erichroepke/Desktop/Cornelius/resources/brain-graph/daily/digest.py` after the daily sweep completed.",
        "",
        "## Inventory sweep",
        "",
        f"- **New files discovered**: {n_swept}",
        "",
        "## Router decisions",
        "",
    ]

    if routed:
        lines.append("| Destination | Count |")
        lines.append("|---|---|")
        for dest, count in routed:
            lines.append(f"| `{dest}` | {count} |")
    else:
        lines.append("_No routing decisions today._")
    lines.append("")

    lines.extend(["## Processor invocations", ""])
    if processed:
        lines.append("| Skill | Count |")
        lines.append("|---|---|")
        for skill, count in processed:
            lines.append(f"| `{skill}` | {count} |")
    else:
        lines.append("_No skill invocations today._")
    lines.append("")

    lines.extend(["## Enricher", ""])
    if enriched:
        lines.append("| Step | Status | Count |")
        lines.append("|---|---|---|")
        for step, status, count in enriched:
            lines.append(f"| `{step}` | `{status}` | {count} |")
    else:
        lines.append("_Enricher did not run today._")
    lines.append("")

    lines.extend([
        "## Rollback",
        "",
        f"Reverse today's ingestion with:",
        "",
        "```bash",
        f"python -m daily.cli rollback {date_str}",
        "```",
        "",
        "Audit log: `/Users/erichroepke/Desktop/Cornelius/resources/brain-graph/data/daily_audit.db`",
    ])

    text = "\n".join(lines) + "\n"
    out_path.write_text(text)
    return out_path


if __name__ == "__main__":
    p = write_digest()
    print(f"Digest written: {p}")
